In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

df1 = pd.read_csv('demographics.csv', usecols=['Age_at_V1','PublicID','CRace'],encoding='latin-1')

columns_to_use = ['V1AF02', 'V1AF14', 'V1AF10','PublicID']

df2 = pd.read_csv('V1A.csv', usecols=columns_to_use,encoding='latin-1')

merged_df = pd.merge(df1, df2, on='PublicID', how='inner')

In [3]:
merged_df=merged_df.dropna()

columns_to_convert = ['Age_at_V1', 'V1AF02', 'V1AF10','CRace']

merged_df.loc[:, columns_to_convert] = merged_df.loc[:, columns_to_convert].astype(int)

In [4]:

healthcare_columns = ['V1AF15a', 'V1AF15b', 'V1AF15c', 'V1AF15d', 'V1AF15e', 'V1AF15f', 'V1AF15g','PublicID']

df = pd.read_csv('V1A.CSV', usecols=healthcare_columns)

df['has_healthcare'] = 0

for index, row in df.iterrows():
    for column in healthcare_columns:
        if row[column] == 1:
            df.at[index, 'has_healthcare'] = 1  # 'Has_Healthcare' 1 if individual has healthcare
            break
        elif row[column] == 0:
            df.at[index, 'has_healthcare'] = 0  # 'Has_Healthcare' 0 if individual does not have healthcare
            break

In [5]:
merged_df = pd.merge(merged_df, df[['PublicID','has_healthcare']], on='PublicID', how='inner')

# df = df.drop(['level_0','index'], axis=1)

In [6]:
df_out = pd.read_csv('outcome.csv',usecols=['PublicID','MH_outcome'])

In [7]:
merged_df = pd.merge(merged_df, df_out, on='PublicID', how='inner')
# merged_df=merged_df.dropna(inplace=True)

In [8]:
print(merged_df)

     PublicID  Age_at_V1  CRace  V1AF02  V1AF10 V1AF14  has_healthcare  \
0      00004O       21.0    3.0     4.0     1.0      5               0
1      00007I       19.0    1.0     4.0     1.0      4               1
2      00008G       30.0    1.0     3.0     1.0     10               0
3      00015J       32.0    1.0     7.0     1.0     12               0
4      00016H       21.0    2.0     3.0     1.0      7               1
...       ...        ...    ...     ...     ...    ...             ...
7734   17349I       23.0    1.0     4.0     1.0      3               0
7735   17350A       22.0    1.0     4.0     1.0      4               1
7736   17351V       40.0    1.0     7.0     1.0     11               0
7737   17352T       31.0    4.0     8.0     1.0     13               0
7738   17354P       19.0    3.0     5.0     1.0      3               1

      MH_outcome
0              1
1              1
2              0
3              0
4              1
...          ...
7734           1
7735           1
7736           0
7737           1
7738           1

[7739 rows x 8 columns]

In [9]:
merged_df = merged_df[merged_df['V1AF14'] != 'D']
merged_df = merged_df[merged_df['V1AF14'] != 'R']
# merged_df['V1AF10'] = 5 - merged_df['V1AF10']

In [10]:
merged_df = merged_df.dropna()
print(merged_df)

     PublicID  Age_at_V1  CRace  V1AF02  V1AF10 V1AF14  has_healthcare  \
0      00004O       21.0    3.0     4.0     1.0      5               0
1      00007I       19.0    1.0     4.0     1.0      4               1
2      00008G       30.0    1.0     3.0     1.0     10               0
3      00015J       32.0    1.0     7.0     1.0     12               0
4      00016H       21.0    2.0     3.0     1.0      7               1
...       ...        ...    ...     ...     ...    ...             ...
7734   17349I       23.0    1.0     4.0     1.0      3               0
7735   17350A       22.0    1.0     4.0     1.0      4               1
7736   17351V       40.0    1.0     7.0     1.0     11               0
7737   17352T       31.0    4.0     8.0     1.0     13               0
7738   17354P       19.0    3.0     5.0     1.0      3               1

      MH_outcome
0              1
1              1
2              0
3              0
4              1
...          ...
7734           1
7735           1
7736           0
7737           1
7738           1

[6411 rows x 8 columns]

In [11]:
# X = merged_df.drop(['PublicID','MH_outcome','V4AH01'],axis=1)
# # y = merged_df.drop(['PublicID','Age_at_V1','V1AF02','Race','V1AF10','V1AF14','has_healthcare','Birth_Weight_Category','CBAA04a','CBAA04b','Birth_Type','Preterm_Birth_Category','MH_outcome'],axis=1)
# y= merged_df[['V4AH01']]

In [12]:
# X = df[['V1AF02','V1AF10','DT_VITB6','DT_SUG_T','DT_THIA','DT_ALCO','DT_SODI','DT_RIBO','DT_VITB6','AHEI_PUFAPCT','sleep_SE_avg_all_Mod','sleep_sleeptime_avg_all_Mod']]

In [13]:
# y = merged_df['V4AH01']

In [14]:

# y = y.drop(['CBAA04a','CBAA04b','Birth_Weight_Category','Birth_Type','Preterm_Birth_Category','V4AH01'],axis=1)

In [15]:
# y['CBAA04b'] = y['CBAA04b'].astype(float)
# y['CBAA04a'] = y['CBAA04a'].astype(float)

# y['CBAA04a'] = y['CBAA04a'].apply(lambda x: 0 if x < 7 else 1)
# y['CBAA04b'] = y['CBAA04b'].apply(lambda x: 0 if x < 7 else 1)

In [16]:
#food
food_predictors = ['DT_FOLAC', 'DT_CALC', 'VITD_MCG', 'TOTAL_CHOLINE', 'DT_SODI','PRENATALAMOUNT','AHEI2010','DT_ALCO','DT_CAFFN','DT_FIBE','DT_SUG_T','DT_CHOL','DT_PFAT','DT_MFAT','DT_SFAT','DT_TFAT','DT_CARB','DT_KCAL', 'DT_PROT','DT_VITC', 'DT_VB12', 'DT_VITB6','DT_RIBO','DT_THIA', 'DT_IRON', 'DT_TOTN3']
df_food = pd.read_csv('FOOD_FREQUENCY_ANALYSIS.csv', usecols=food_predictors + ['PublicID'])
df = pd.merge(merged_df, df_food, on='PublicID', how='inner')

df

,PublicID,Age_at_V1,CRace,V1AF02,V1AF10,V1AF14,has_healthcare,MH_outcome,DT_KCAL,DT_PROT,...,DT_IRON,DT_SODI,DT_VITC,DT_THIA,DT_RIBO,DT_VITB6,DT_VB12,DT_TOTN3,PRENATALAMOUNT,AHEI2010
0,00004O,21.0,3.0,4.0,1.0,5,0,1,1445.22,55.33,...,9.19,2377.93,110.10,0.929,1.060,1.130,2.61,1.790,1,52.410880
1,00008G,30.0,1.0,3.0,1.0,10,0,0,1472.37,48.61,...,11.14,2379.80,146.56,1.120,1.440,1.680,3.70,1.060,1,53.209509
2,00015J,32.0,1.0,7.0,1.0,12,0,0,2162.19,98.57,...,21.15,4489.82,148.04,2.060,2.820,2.690,6.95,2.610,5,70.084156
3,00016H,21.0,2.0,3.0,1.0,7,1,1,1014.46,32.44,...,5.11,1632.50,52.26,0.575,0.614,0.709,1.50,1.640,1,48.539366
4,00017F,34.0,1.0,6.0,1.0,14,0,1,1170.14,39.34,...,12.21,2234.09,160.52,1.540,1.810,2.690,4.35,1.820,1,76.122387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5805,17349I,23.0,1.0,4.0,1.0,3,0,1,1744.90,73.89,...,11.29,2828.63,204.90,1.510,2.460,1.650,6.11,1.120,3,40.753166
5806,17350A,22.0,1.0,4.0,1.0,4,1,1,1289.42,41.81,...,6.63,1702.65,50.40,0.581,0.779,0.981,2.14,1.300,1,38.578954
5807,17351V,40.0,1.0,7.0,1.0,11,0,0,680.02,38.19,...,6.14,1513.87,38.03,0.838,1.100,1.000,2.96,0.553,5,61.258473
5808,17352T,31.0,4.0,8.0,1.0,13,0,1,1066.71,40.32,...,7.73,1845.55,73.81,0.750,1.030,0.871,2.31,1.220,1,68.488125
5809,17354P,19.0,3.0,5.0,1.0,3,1,1,1630.98,50.05,...,9.70,2436.44,134.84,1.040,1.490,1.000,3.61,2.280,5,42.594468

In [17]:
# #less rows
# columns = ['PublicID', 'rest_dur_avg_all_Mod']  

# df_sleep = pd.read_csv('SLEEP_ACTIGRAPHY_MODIFIED.CSV', usecols=columns)
# df = pd.merge(df, df_sleep, on='PublicID', how='inner')
# df

In [18]:
# df = df.dropna()
%store -r scoring_df
scoring_df = scoring_df.drop(['MH_outcome','sum','SubSTAIScore','SubEDINScore','Sum_If_1'],axis=1)

df = pd.merge(df, scoring_df, on='PublicID', how='inner')
df

,PublicID,Age_at_V1,CRace,V1AF02,V1AF10,V1AF14,has_healthcare,MH_outcome,DT_KCAL,DT_PROT,...,DT_RIBO,DT_VITB6,DT_VB12,DT_TOTN3,PRENATALAMOUNT,AHEI2010,ResilienceLevel,stress_average,HassleUpliftIntensityRatio,StressLevel
0,00004O,21.0,3.0,4.0,1.0,5,0,1,1445.22,55.33,...,1.060,1.130,2.61,1.790,1,52.410880,1,1.846154,0.866667,0.5
1,00008G,30.0,1.0,3.0,1.0,10,0,0,1472.37,48.61,...,1.440,1.680,3.70,1.060,1,53.209509,1,2.076923,0.916667,0.5
2,00015J,32.0,1.0,7.0,1.0,12,0,0,2162.19,98.57,...,2.820,2.690,6.95,2.610,5,70.084156,1,1.692308,0.350000,0.0
3,00016H,21.0,2.0,3.0,1.0,7,1,1,1014.46,32.44,...,0.614,0.709,1.50,1.640,1,48.539366,2,2.000000,0.652174,0.5
4,00017F,34.0,1.0,6.0,1.0,14,0,1,1170.14,39.34,...,1.810,2.690,4.35,1.820,1,76.122387,2,1.538462,0.703704,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5372,17343U,28.0,1.0,8.0,1.0,11,0,1,1380.88,64.62,...,2.150,1.570,4.39,0.867,5,57.461101,2,1.666667,0.666667,0.0
5373,17345Q,29.0,1.0,6.0,1.0,14,0,0,2209.55,86.18,...,2.800,2.570,6.67,2.110,5,68.034835,1,1.692308,0.633333,0.0
5374,17349I,23.0,1.0,4.0,1.0,3,0,1,1744.90,73.89,...,2.460,1.650,6.11,1.120,3,40.753166,2,1.461538,0.708333,0.5
5375,17352T,31.0,4.0,8.0,1.0,13,0,1,1066.71,40.32,...,1.030,0.871,2.31,1.220,1,68.488125,2,1.538462,0.388889,0.5
5376,17354P,19.0,3.0,5.0,1.0,3,1,1,1630.98,50.05,...,1.490,1.000,3.61,2.280,5,42.594468,1,1.461538,0.250000,0.5

In [19]:
# %store -r df_drugs
# df_drugs = df_drugs.drop(['MH_outcome'],axis=1)

# df = pd.merge(df, df_drugs, on='PublicID', how='inner')
# df

In [20]:
%store -r df_maternal
df_maternal = df_maternal.drop(['MH_outcome','acog_PEgHTN','oDM','CMAE14','CMAE08'],axis=1)

df = pd.merge(df, df_maternal, on='PublicID', how='inner')
df

,PublicID,Age_at_V1,CRace,V1AF02,V1AF10,V1AF14,has_healthcare,MH_outcome,DT_KCAL,DT_PROT,...,DT_VITB6,DT_VB12,DT_TOTN3,PRENATALAMOUNT,AHEI2010,ResilienceLevel,stress_average,HassleUpliftIntensityRatio,StressLevel,ChronHTN
0,00004O,21.0,3.0,4.0,1.0,5,0,1,1445.22,55.33,...,1.130,2.61,1.790,1,52.410880,1,1.846154,0.866667,0.5,2.0
1,00008G,30.0,1.0,3.0,1.0,10,0,0,1472.37,48.61,...,1.680,3.70,1.060,1,53.209509,1,2.076923,0.916667,0.5,2.0
2,00015J,32.0,1.0,7.0,1.0,12,0,0,2162.19,98.57,...,2.690,6.95,2.610,5,70.084156,1,1.692308,0.350000,0.0,2.0
3,00016H,21.0,2.0,3.0,1.0,7,1,1,1014.46,32.44,...,0.709,1.50,1.640,1,48.539366,2,2.000000,0.652174,0.5,2.0
4,00017F,34.0,1.0,6.0,1.0,14,0,1,1170.14,39.34,...,2.690,4.35,1.820,1,76.122387,2,1.538462,0.703704,0.5,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5361,17343U,28.0,1.0,8.0,1.0,11,0,1,1380.88,64.62,...,1.570,4.39,0.867,5,57.461101,2,1.666667,0.666667,0.0,2.0
5362,17345Q,29.0,1.0,6.0,1.0,14,0,0,2209.55,86.18,...,2.570,6.67,2.110,5,68.034835,1,1.692308,0.633333,0.0,2.0
5363,17349I,23.0,1.0,4.0,1.0,3,0,1,1744.90,73.89,...,1.650,6.11,1.120,3,40.753166,2,1.461538,0.708333,0.5,2.0
5364,17352T,31.0,4.0,8.0,1.0,13,0,1,1066.71,40.32,...,0.871,2.31,1.220,1,68.488125,2,1.538462,0.388889,0.5,2.0
5365,17354P,19.0,3.0,5.0,1.0,3,1,1,1630.98,50.05,...,1.000,3.61,2.280,5,42.594468,1,1.461538,0.250000,0.5,2.0

In [21]:
# # 5.3k-.3.1k
%store -r df_health
df_health = df_health[['PublicID','sum_column']]

df = pd.merge(df, df_health, on='PublicID', how='inner')
df

,PublicID,Age_at_V1,CRace,V1AF02,V1AF10,V1AF14,has_healthcare,MH_outcome,DT_KCAL,DT_PROT,...,DT_VB12,DT_TOTN3,PRENATALAMOUNT,AHEI2010,ResilienceLevel,stress_average,HassleUpliftIntensityRatio,StressLevel,ChronHTN,sum_column
0,00004O,21.0,3.0,4.0,1.0,5,0,1,1445.22,55.33,...,2.61,1.790,1,52.410880,1,1.846154,0.866667,0.5,2.0,5.0
1,00008G,30.0,1.0,3.0,1.0,10,0,0,1472.37,48.61,...,3.70,1.060,1,53.209509,1,2.076923,0.916667,0.5,2.0,8.0
2,00017F,34.0,1.0,6.0,1.0,14,0,1,1170.14,39.34,...,4.35,1.820,1,76.122387,2,1.538462,0.703704,0.5,2.0,4.0
3,00027C,26.0,2.0,4.0,1.0,3,1,0,793.36,25.49,...,1.37,0.545,1,38.488076,1,1.076923,0.250000,0.5,2.0,0.0
4,00030N,23.0,3.0,5.0,1.0,9,0,0,770.63,25.21,...,1.35,0.652,1,54.652438,1,1.384615,1.500000,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,17325W,26.0,3.0,6.0,1.0,10,0,0,1346.51,60.00,...,4.11,1.110,5,64.741058,1,1.153846,0.250000,0.5,2.0,9.0
3184,17331E,31.0,3.0,4.0,1.0,11,1,0,1097.35,49.10,...,4.34,0.697,5,46.392999,1,2.083333,0.575758,0.5,2.0,0.0
3185,17343U,28.0,1.0,8.0,1.0,11,0,1,1380.88,64.62,...,4.39,0.867,5,57.461101,2,1.666667,0.666667,0.0,2.0,7.0
3186,17345Q,29.0,1.0,6.0,1.0,14,0,0,2209.55,86.18,...,6.67,2.110,5,68.034835,1,1.692308,0.633333,0.0,2.0,1.0
3187,17352T,31.0,4.0,8.0,1.0,13,0,1,1066.71,40.32,...,2.31,1.220,1,68.488125,2,1.538462,0.388889,0.5,2.0,0.0

In [22]:
df

,PublicID,Age_at_V1,CRace,V1AF02,V1AF10,V1AF14,has_healthcare,MH_outcome,DT_KCAL,DT_PROT,...,DT_VB12,DT_TOTN3,PRENATALAMOUNT,AHEI2010,ResilienceLevel,stress_average,HassleUpliftIntensityRatio,StressLevel,ChronHTN,sum_column
0,00004O,21.0,3.0,4.0,1.0,5,0,1,1445.22,55.33,...,2.61,1.790,1,52.410880,1,1.846154,0.866667,0.5,2.0,5.0
1,00008G,30.0,1.0,3.0,1.0,10,0,0,1472.37,48.61,...,3.70,1.060,1,53.209509,1,2.076923,0.916667,0.5,2.0,8.0
2,00017F,34.0,1.0,6.0,1.0,14,0,1,1170.14,39.34,...,4.35,1.820,1,76.122387,2,1.538462,0.703704,0.5,2.0,4.0
3,00027C,26.0,2.0,4.0,1.0,3,1,0,793.36,25.49,...,1.37,0.545,1,38.488076,1,1.076923,0.250000,0.5,2.0,0.0
4,00030N,23.0,3.0,5.0,1.0,9,0,0,770.63,25.21,...,1.35,0.652,1,54.652438,1,1.384615,1.500000,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,17325W,26.0,3.0,6.0,1.0,10,0,0,1346.51,60.00,...,4.11,1.110,5,64.741058,1,1.153846,0.250000,0.5,2.0,9.0
3184,17331E,31.0,3.0,4.0,1.0,11,1,0,1097.35,49.10,...,4.34,0.697,5,46.392999,1,2.083333,0.575758,0.5,2.0,0.0
3185,17343U,28.0,1.0,8.0,1.0,11,0,1,1380.88,64.62,...,4.39,0.867,5,57.461101,2,1.666667,0.666667,0.0,2.0,7.0
3186,17345Q,29.0,1.0,6.0,1.0,14,0,0,2209.55,86.18,...,6.67,2.110,5,68.034835,1,1.692308,0.633333,0.0,2.0,1.0
3187,17352T,31.0,4.0,8.0,1.0,13,0,1,1066.71,40.32,...,2.31,1.220,1,68.488125,2,1.538462,0.388889,0.5,2.0,0.0

In [23]:
#3k->2.5k rows
%store -r df_pa
df_pa = df_pa[['V2AJ01a1','V2AJ01a2','PublicID']]
df = pd.merge(df, df_pa, on='PublicID', how='inner')
df

,PublicID,Age_at_V1,CRace,V1AF02,V1AF10,V1AF14,has_healthcare,MH_outcome,DT_KCAL,DT_PROT,...,PRENATALAMOUNT,AHEI2010,ResilienceLevel,stress_average,HassleUpliftIntensityRatio,StressLevel,ChronHTN,sum_column,V2AJ01a1,V2AJ01a2
0,00008G,30.0,1.0,3.0,1.0,10,0,0,1472.37,48.61,...,1,53.209509,1,2.076923,0.916667,0.5,2.0,8.0,3.0,0.040334
1,00017F,34.0,1.0,6.0,1.0,14,0,1,1170.14,39.34,...,1,76.122387,2,1.538462,0.703704,0.5,2.0,4.0,3.0,0.082058
2,00027C,26.0,2.0,4.0,1.0,3,1,0,793.36,25.49,...,1,38.488076,1,1.076923,0.250000,0.5,2.0,0.0,7.0,0.165508
3,00030N,23.0,3.0,5.0,1.0,9,0,0,770.63,25.21,...,1,54.652438,1,1.384615,1.500000,0.0,2.0,0.0,1.0,0.061196
4,00033H,31.0,4.0,7.0,2.0,12,0,0,1447.29,40.39,...,1,67.110524,2,1.692308,1.045455,0.5,2.0,0.0,5.0,0.054242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,17325W,26.0,3.0,6.0,1.0,10,0,0,1346.51,60.00,...,5,64.741058,1,1.153846,0.250000,0.5,2.0,9.0,2.0,0.061196
2439,17331E,31.0,3.0,4.0,1.0,11,1,0,1097.35,49.10,...,5,46.392999,1,2.083333,0.575758,0.5,2.0,0.0,1.0,0.082058
2440,17343U,28.0,1.0,8.0,1.0,11,0,1,1380.88,64.62,...,5,57.461101,2,1.666667,0.666667,0.0,2.0,7.0,1.0,0.102921
2441,17345Q,29.0,1.0,6.0,1.0,14,0,0,2209.55,86.18,...,5,68.034835,1,1.692308,0.633333,0.0,2.0,1.0,2.0,0.040334
2442,17352T,31.0,4.0,8.0,1.0,13,0,1,1066.71,40.32,...,1,68.488125,2,1.538462,0.388889,0.5,2.0,0.0,1.0,0.040334

In [24]:
# y = y.drop(['MH_outcome','V4AH01'],axis=1)
# df = df.drop(['V1AF15a','V1AF15b','V1AF15c','V1AF15d','V1AF15e','V1AF15f','V1AF15g'], axis =1)
# for column in df.columns:
#         df = df.loc[~df[column].isin[['E']]]


# Apply the mask to the DataFrame to filter out unwanted rows
# df.replace('M', np.nan, inplace=True)
# df.dropna(inplace=True)
# df = df.apply(pd.to_numeric, errors='coerce')

In [25]:
cols_with_M = df.columns[df.isin(['M']).any()].tolist()

# Replace 'M' with NaN and then fill or drop
for col in cols_with_M:
    df[col] = pd.to_numeric(df[col], errors='coerce') 
    df.dropna(subset=[col],inplace=True)

In [90]:
# X_train_smote
df

,PublicID,Age_at_V1,CRace,V1AF02,V1AF10,V1AF14,has_healthcare,MH_outcome,DT_KCAL,DT_PROT,...,PRENATALAMOUNT,AHEI2010,ResilienceLevel,stress_average,HassleUpliftIntensityRatio,StressLevel,ChronHTN,sum_column,V2AJ01a1,V2AJ01a2
0,00008G,30.0,1.0,3.0,1.0,10,0,0,1472.37,48.61,...,1.0,53.209509,1,2.076923,0.916667,0.5,2.0,8.0,3.0,0.040334
1,00017F,34.0,1.0,6.0,1.0,14,0,1,1170.14,39.34,...,1.0,76.122387,2,1.538462,0.703704,0.5,2.0,4.0,3.0,0.082058
2,00027C,26.0,2.0,4.0,1.0,3,1,0,793.36,25.49,...,1.0,38.488076,1,1.076923,0.250000,0.5,2.0,0.0,7.0,0.165508
3,00030N,23.0,3.0,5.0,1.0,9,0,0,770.63,25.21,...,1.0,54.652438,1,1.384615,1.500000,0.0,2.0,0.0,1.0,0.061196
4,00033H,31.0,4.0,7.0,2.0,12,0,0,1447.29,40.39,...,1.0,67.110524,2,1.692308,1.045455,0.5,2.0,0.0,5.0,0.054242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,17325W,26.0,3.0,6.0,1.0,10,0,0,1346.51,60.00,...,5.0,64.741058,1,1.153846,0.250000,0.5,2.0,9.0,2.0,0.061196
2439,17331E,31.0,3.0,4.0,1.0,11,1,0,1097.35,49.10,...,5.0,46.392999,1,2.083333,0.575758,0.5,2.0,0.0,1.0,0.082058
2440,17343U,28.0,1.0,8.0,1.0,11,0,1,1380.88,64.62,...,5.0,57.461101,2,1.666667,0.666667,0.0,2.0,7.0,1.0,0.102921
2441,17345Q,29.0,1.0,6.0,1.0,14,0,0,2209.55,86.18,...,5.0,68.034835,1,1.692308,0.633333,0.0,2.0,1.0,2.0,0.040334
2442,17352T,31.0,4.0,8.0,1.0,13,0,1,1066.71,40.32,...,1.0,68.488125,2,1.538462,0.388889,0.5,2.0,0.0,1.0,0.040334

In [28]:
categorical_features = ['CRace','V1AF14','V1AF10','V1AF02','PRENATALAMOUNT']  
continuous_features = ['Age_at_V1', 'DT_KCAL', 'DT_PROT', 'DT_CARB', 'DT_TFAT', 'DT_ALCO','DT_CAFFN','VITD_MCG','TOTAL_CHOLINE','DT_FOLAC','DT_SUG_T','DT_FIBE','DT_CHOL','DT_SFAT','DT_MFAT','DT_PFAT','DT_CALC','DT_IRON','DT_SODI','DT_VITC','DT_THIA','DT_RIBO','DT_VITB6','DT_VB12','DT_TOTN3','AHEI2010','V2AJ01a2']

In [29]:
X = df.drop(['PublicID','MH_outcome'],axis =1)
y = df['MH_outcome']

In [33]:
df.to_csv('mother_demo_df.csv', index=False)

In [74]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, StratifiedKFold
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import numpy as np

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = MinMaxScaler()
X_train_continuous = scaler.fit_transform(X_train[continuous_features])  # Normalize continuous features
X_train[continuous_features] = X_train_continuous  # Update the training set with normalized data

X_test_continuous = scaler.transform(X_test[continuous_features])  # Apply the same transformation to test data
X_test[continuous_features] = X_test_continuous  # Update the test set with normalized data


# Apply SMOTE to balance the training data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
X_train_smote = pd.DataFrame(X_train_smote, columns=X_train.columns)
X_test = pd.DataFrame(X_test, columns=X_train.columns)

# Initialize the logistic regression model and feature selector
model = LogisticRegression(solver='liblinear',penalty ='l2',C=0.01,max_iter=1000)
selector = RFECV(estimator=model, step=1, cv=StratifiedKFold(5), scoring='f1', min_features_to_select=10)
selector.fit(X_train_smote, y_train_smote)

# mean_test_scores = selector.cv_results_['mean_test_score']

# The optimal number of features is determined by RFECV
selected_features = X_train_smote.columns[selector.support_]

print(f"Optimal number of features: {selector.n_features_}")
print(f"Selected features: {selected_features.tolist()}")

# To proceed with logistic regression using the selected features:
model.fit(X_train_smote.loc[:, selector.support_], y_train_smote)
y_pred = model.predict(X_test.loc[:, selector.support_])

# # Evaluate the model
print(classification_report(y_test, y_pred))

# Print the model coefficients
print("Model Coefficients:")
for feature, coef in zip(selected_features, model.coef_[0]):
    print(f"{feature}: {coef}")

Optimal number of features: 10
Selected features: ['Age_at_V1', 'V1AF02', 'V1AF14', 'has_healthcare', 'AHEI2010', 'ResilienceLevel', 'stress_average', 'HassleUpliftIntensityRatio', 'StressLevel', 'ChronHTN']
              precision    recall  f1-score   support

           0       0.79      0.68      0.74       298
           1       0.58      0.71      0.64       185

    accuracy                           0.70       483
   macro avg       0.69      0.70      0.69       483
weighted avg       0.71      0.70      0.70       483

Model Coefficients:
Age_at_V1: 0.062416292068181015
V1AF02: -0.1428802022373499
V1AF14: -0.06088803562028747
has_healthcare: -0.11958485720744211
AHEI2010: -0.0691551761838033
ResilienceLevel: 0.39768744214891444
stress_average: 0.5955321027528846
HassleUpliftIntensityRatio: 0.45468173525817873
StressLevel: 0.4830350915048377
ChronHTN: -0.18189568440955825

In [85]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, StratifiedKFold
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import pandas as pd
import numpy as np

# Assume X, y, continuous_features, categorical_features are defined

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the preprocessor for scaling and encoding
preprocessor = ColumnTransformer(
    transformers=[
        ('num', MinMaxScaler(), continuous_features),  # Scale continuous features
        ('cat', OneHotEncoder(drop='first'), categorical_features)  # One-hot encode categorical features
    ]
)

# Apply preprocessing to the training and test sets
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

# Apply SMOTE to balance the training data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Convert the transformed training data back to a DataFrame to maintain feature names
feature_names = preprocessor.get_feature_names_out()
X_train_smote = pd.DataFrame(X_train_smote, columns=feature_names)

# Initialize the logistic regression model and feature selector
model = LogisticRegression(solver='saga', penalty='elasticnet', l1_ratio=0.5, C=0.01, max_iter=1000)
selector = RFECV(estimator=model, step=1, cv=StratifiedKFold(4), scoring='f1', min_features_to_select=10)

# Fit the RFECV model
selector.fit(X_train_smote, y_train_smote)

# Determine the optimal features and refit the model
selected_features = X_train_smote.columns[selector.support_]
print(f"Optimal number of features: {selector.n_features_}")
print(f"Selected features: {selected_features.tolist()}")

# Re-train model using only selected features
model.fit(X_train_smote[selected_features], y_train_smote)

# Transform the test set based on the selected features
X_test_selected = pd.DataFrame(X_test, columns=feature_names)[selected_features]

# Predict and evaluate model on the test set
y_pred = model.predict(X_test_selected)
print(classification_report(y_test, y_pred))

# Print coefficients for selected features
print("Model Coefficients for Selected Features:")
for feature, coef in zip(selected_features, model.coef_[0]):
    print(f"{feature}: {coef}")

Optimal number of features: 10
Selected features: ['cat__V1AF02_3.0', 'cat__V1AF02_4.0', 'cat__V1AF02_5.0', 'cat__V1AF02_6.0', 'cat__V1AF02_7.0', 'cat__V1AF02_8.0', 'cat__PRENATALAMOUNT_2.0', 'cat__PRENATALAMOUNT_3.0', 'cat__PRENATALAMOUNT_4.0', 'cat__PRENATALAMOUNT_5.0']
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       298
           1       0.38      1.00      0.55       185

    accuracy                           0.38       483
   macro avg       0.19      0.50      0.28       483
weighted avg       0.15      0.38      0.21       483

Model Coefficients for Selected Features:
cat__V1AF02_3.0: 0.0
cat__V1AF02_4.0: 0.0
cat__V1AF02_5.0: 0.0
cat__V1AF02_6.0: 0.0
cat__V1AF02_7.0: 0.0
cat__V1AF02_8.0: 0.0
cat__PRENATALAMOUNT_2.0: 0.0
cat__PRENATALAMOUNT_3.0: 0.0
cat__PRENATALAMOUNT_4.0: 0.0
cat__PRENATALAMOUNT_5.0: 0.0

C:\Users\91799\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\91799\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\91799\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [89]:
# Assuming X_train is a NumPy array
num_rows = X_train.shape[0]
print(f"Number of rows in X_train: {num_rows}")

Number of rows in X_train: 1932

In [81]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np

# Define preprocessing for continuous and categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), continuous_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

# Create a pipeline for feature selection and model training
pipeline = ImbPipeline(steps=[
    ('preprocessor', preprocessor),
    ('feature_selection', SelectKBest(score_func=f_classif, k='all')),
    ('smote', SMOTE(random_state=42)),
    ('classifier', LogisticRegression(solver='saga', penalty='elasticnet', l1_ratio=0.5, C=0.1, max_iter=1000))
])

# Fit the pipeline
pipeline.fit(X_train, y_train)

# Feature selection
feature_selector = pipeline.named_steps['feature_selection']
support_mask = feature_selector.get_support()

# Retrieve the feature names after preprocessing
preprocessor = pipeline.named_steps['preprocessor']
feature_names = []

# Handle the feature names extraction correctly
for name, transformer, columns in preprocessor.transformers_:
    if name == 'num':
        feature_names.extend(columns)
    elif name == 'cat':
        encoded_feature_names = transformer.get_feature_names_out(columns)
        feature_names.extend(encoded_feature_names)

# Use the correct number of features
selected_features = np.array(feature_names)[support_mask]

print("Feature Scores:", feature_selector.scores_)
print("Selected Features:", selected_features.tolist())

# Evaluate the pipeline
y_pred = pipeline.predict(X_test)
print(classification_report(y_test, y_pred))

ValueError: Specifying the columns using strings is only supported for pandas DataFrames

In [60]:
# Retrain the model with the best hyperparameters found
best_model = LogisticRegression(solver='liblinear', penalty='l1', C=0.01, max_iter=500)
best_model.fit(X_train, y_train_smote)
# Predict on the test set
y_pred = best_model.predict(X_test)

# Evaluate the model
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))
# Check the coefficients of the trained logistic regression model
feature_importance = best_model.coef_[0]

# Pair coefficients with feature names
important_features = [(feature, coef) for feature, coef in zip(feature_selector.get_feature_names_out(), feature_importance) if coef != 0]

# Print important features
print("Important Features and Coefficients:")
for feature, coef in important_features:
    print(f"{feature}: {coef}")

ValueError: Found input variables with inconsistent numbers of samples: [1932, 2496]

In [35]:
# missing_continuous_features = [feature for feature in continuous_features if feature not in X_train.columns]
# print("Missing continuous features:", missing_continuous_features)

Missing continuous features: []

In [55]:
from sklearn.model_selection import GridSearchCV

# Parameter grid
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}

# Grid search for hyperparameter tuning
grid_search = GridSearchCV(estimator=LogisticRegression(solver='liblinear', penalty='l1', max_iter=500),
                           param_grid=param_grid,
                           scoring='recall',
                           cv=5)
grid_search.fit(X_train_smote.loc[:, feature_selector.get_support()], y_train_smote)

print("Best hyperparameters:", grid_search.best_params_)

IndexError: Boolean index has wrong length: 62 instead of 40

In [57]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np

# Assume X, y, continuous_features, and categorical_features are defined
# Define preprocessing for continuous and categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), continuous_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

# Apply preprocessing pipeline first
X_train_preprocessed = preprocessor.fit_transform(X_train)
X_test_preprocessed = preprocessor.transform(X_test)

# Apply SMOTE to preprocessed data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_preprocessed, y_train)

# Fit feature selection after SMOTE
feature_selector = SelectKBest(score_func=f_classif, k='all')
X_train_selected = feature_selector.fit_transform(X_train_smote, y_train_smote)
X_test_selected = feature_selector.transform(X_test_preprocessed)

# Initialize grid search with Logistic Regression
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}
grid_search = GridSearchCV(estimator=LogisticRegression(solver='liblinear', penalty='l1', max_iter=500),
                           param_grid=param_grid,
                           scoring='recall',
                           cv=5)

# Fit grid search on the transformed data
grid_search.fit(X_train_selected, y_train_smote)

print("Best hyperparameters:", grid_search.best_params_)

Best hyperparameters: {'C': 0.01}

In [ ]:
model.fit(X_train_smote.loc[:, selector.support_], y_train_smote)

# Get probability scores for the positive class
probabilities = model.predict_proba(X_test.loc[:, selector.support_])[:, 1]

# Choose a threshold
threshold = 0.55  # You can adjust this threshold based on your requirement

# Apply threshold to probability scores to get custom predictions
y_predc = (probabilities >= threshold).astype(int)

# Now generate the classification report using the custom predictions
print(classification_report(y_test, y_predc))

# If you wish to display which features were selected and their coefficients
print("Model Coefficients for Selected Features:")
for feature, coef in zip(optimal_features, model.coef_[0]):
    print(f"{feature}: {coef}")

In [37]:
from sklearn.ensemble import RandomForestClassifier

# ... (The earlier parts of your code where you define X, y, and split the data remain the same)

# Initialize the RandomForestClassifier model
rf_model = RandomForestClassifier(random_state=42)

# Apply MinMaxScaler and SMOTE to your training data as before
# ...

# Since feature selection with RFECV can be computationally expensive and isn't always necessary with tree-based methods, 
# you might choose to omit RFECV and use the full feature set, or use a different feature selection method that's 
# more suited to RandomForestClassifier.

# Fit the RandomForestClassifier model on the balanced training data
rf_model.fit(X_train_smote, y_train_smote)

# Predict on the test data
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred_rf))

# Feature importances can be obtained directly from the RandomForestClassifier
print("Feature importances:")
for feature, importance in zip(X_train.columns, rf_model.feature_importances_):
    print(f"{feature}: {importance}")

              precision    recall  f1-score   support

           0       0.78      0.83      0.81       298
           1       0.70      0.62      0.66       185

    accuracy                           0.75       483
   macro avg       0.74      0.73      0.73       483
weighted avg       0.75      0.75      0.75       483

Feature importances:
Age_at_V1: 0.02723828409364333
CRace: 0.008561387787044844
V1AF02: 0.02581429697814525
V1AF10: 0.0019859930266441462
V1AF14: 0.027725268941678295
has_healthcare: 0.0023747773049175793
DT_KCAL: 0.019450013471412654
DT_PROT: 0.020227782626334796
DT_CARB: 0.020890028966123894
DT_TFAT: 0.02260679338096828
DT_ALCO: 0.024374571397764798
DT_CAFFN: 0.027316841132585507
VITD_MCG: 0.027148939896397457
TOTAL_CHOLINE: 0.02297530217410074
DT_FOLAC: 0.025777280166165917
DT_SUG_T: 0.023855356683216623
DT_FIBE: 0.022207654794916803
DT_CHOL: 0.025690529487097834
DT_SFAT: 0.022858180661245606
DT_MFAT: 0.02371003417433404
DT_PFAT: 0.023087483420497667
DT_CALC: 0.023265966301911384
DT_IRON: 0.021664227227883092
DT_SODI: 0.02065218429240087
DT_VITC: 0.02428948697520348
DT_THIA: 0.02091777668060176
DT_RIBO: 0.022642851912768713
DT_VITB6: 0.020724148033776205
DT_VB12: 0.022148428989576346
DT_TOTN3: 0.02549526270994683
PRENATALAMOUNT: 0.008284422054742136
AHEI2010: 0.028961163318634454
ResilienceLevel: 0.019324449718806105
stress_average: 0.09737432124093508
HassleUpliftIntensityRatio: 0.05969008416046087
StressLevel: 0.08236080358829817
ChronHTN: 0.0017537519053389477
sum_column: 0.018973571537031247
V2AJ01a1: 0.01610526809804779
V2AJ01a2: 0.019495030688400493

In [39]:
accuracy = accuracy_score(y_test, y_predc)
precision = precision_score(y_test, y_predc, average='weighted')
recall = recall_score(y_test, y_predc,average='weighted')
f1 = f1_score(y_test, y_predc,average='weighted')
# roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")
print(classification_report(y_test, y_pred))

NameError: name 'y_predc' is not defined

In [ ]:
# merged_df_scaled = merged_df_scaled.drop(['V1AF02','V1AF14'], axis=1)

In [40]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform

hyperparameter_space = {
    'C': uniform(loc=0, scale=10),  # Regularization parameter (inverse of lambda)
    'solver': [ 'lbfgs', 'saga'],  # Solvers for optimization
    'penalty': ['none', 'l2']  # Regularization type ('l1' for Lasso, 'l2' for Ridge)
}

logistic_model = LogisticRegression(penalty='l2', solver='liblinear')

random_search = RandomizedSearchCV(
    estimator=logistic_model,
    param_distributions=hyperparameter_space,
    n_iter=10,  # Number of random combinations to try
    scoring='precision',  # Use accuracy as the scoring metric
    cv=4,  # Number of cross-validation folds
    random_state=42
)

random_search.fit(X_train, y_train)

best_params = random_search.best_params_
print("Best Hyperparameters:", best_params)

C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.


Best Hyperparameters: {'C': 0.5808361216819946, 'penalty': 'l2', 'solver': 'lbfgs'}

C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:1192: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
y = y.drop(['Birth_Type'],axis=1)

In [41]:
model = LogisticRegression(C=0.34388521115218396, penalty='l2', solver='lbfgs')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

C:\Users\91799\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [42]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

Evaluation Metrics:
Accuracy: 0.7329
Precision: 0.7333
Recall: 0.4757
F1-score: 0.5770
ROC AUC: 0.8126

In [43]:
from sklearn.ensemble import RandomForestClassifier
# from imblearn.over_sampling import SMOTE

# smote = SMOTE(random_state=42)
# X_train, y_train = smote.fit_resample(X_train, y_train)
rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

Evaluation Metrics:
Accuracy: 0.7267
Precision: 0.7304
Recall: 0.4541
F1-score: 0.5600
ROC AUC: 0.6750

In [44]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

# Create a RandomForestRegressor instance
rf_regressor = RandomForestRegressor(random_state=123)

# Fit the model
rf_regressor.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_regressor.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 0.18480269151138717
Mean Absolute Error: 0.3669772256728778
R-squared: 0.21798594050426234

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif

k = 3
selector = SelectKBest(score_func=f_classif, k=k)
X_selected = selector.fit_transform(X_train_resampled, y_train)

selected_feature_names = X_train.columns[selector.get_support()]

X_train_selected = pd.DataFrame(X_selected, columns=selected_feature_names)
X_test_selected = pd.DataFrame(selector.transform(X_test), columns=selected_feature_names)

# model = LogisticRegression(solver='lbfgs')
# model.fit(X_train_selected, y_train)
# y_pred = model.predict(X_test_selected)

# rf_model = RandomForestClassifier(random_state=42)

# rf_model.fit(X_train, y_train)

# y_pred = rf_model.predict(X_test_selected)


accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

In [ ]:
# from sklearn.svm import SVC

# svm_model = SVC(kernel='rbf', C=1.0, random_state=42)

# svm_model.fit(X_train_selected, y_train)

# y_pred = svm_model.predict(X_test_selected)

# accuracy = accuracy_score(y_test, y_pred)
# precision = precision_score(y_test, y_pred)
# recall = recall_score(y_test, y_pred)
# f1 = f1_score(y_test, y_pred)
# roc_auc = roc_auc_score(y_test, y_pred)

# print("Evaluation Metrics:")
# print(f"Accuracy: {accuracy:.4f}")
# print(f"Precision: {precision:.4f}")
# print(f"Recall: {recall:.4f}")
# print(f"F1-score: {f1:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import classification_report
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.compose import ColumnTransformer

# Load the datasets
demographics = pd.read_csv('demographics.csv', usecols=['Age_at_V1', 'PublicID', 'CRace'], encoding='latin-1')
v1a_data = pd.read_csv('V1A.csv', usecols=['V1AF02', 'V1AF14', 'V1AF10', 'PublicID'], encoding='latin-1')
healthcare_data = pd.read_csv('V1A.CSV', usecols=['V1AF15a', 'V1AF15b', 'V1AF15c', 'V1AF15d', 'V1AF15e', 'V1AF15f', 'V1AF15g', 'PublicID'])
outcome_data = pd.read_csv('outcome.csv', usecols=['PublicID', 'MH_outcome'])

# Define your preprocessing
continuous_features = [...]  # List of your continuous features
categorical_features = [...]  # List of your categorical features

# Merge datasets
df = demographics.merge(v1a_data, on='PublicID').merge(outcome_data, on='PublicID')

# Determine 'has_healthcare'
healthcare_data['has_healthcare'] = healthcare_data.filter(regex='V1AF15').eq(1).any(axis=1).astype(int)
df = df.merge(healthcare_data[['PublicID', 'has_healthcare']], on='PublicID')

# Further merges with other datasets can be done similarly...

# Replace 'M' with NaN and drop rows with NaN
df.replace('M', pd.NA, inplace=True)
df.dropna(inplace=True)

# Convert categorical columns to 'category' dtype and continuous features to numeric
# df[categorical_features] = df[categorical_features].astype('category')
df[continuous_features] = df[continuous_features].apply(pd.to_numeric, errors='coerce')

# Split the dataset into features and target variable
X = df.drop(['PublicID', 'MH_outcome'], axis=1)
y = df['MH_outcome'].astype('category')

# Define your pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', ColumnTransformer(transformers=[
        ('num', MinMaxScaler(), continuous_features),
        ('cat', 'passthrough', categorical_features)
    ])),
    ('smote', SMOTE(random_state=42)),
    ('classifier', LogisticRegression(solver='liblinear', penalty='l1', max_iter=100))
])

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature selection
selector = RFECV(estimator=pipeline.named_steps['classifier'], step=1, cv=StratifiedKFold(5), scoring='recall')
X_train_prep = pipeline.named_steps['preprocessor'].fit_transform(X_train)
selector.fit(X_train_prep, y_train)

optimal_features = X.columns[selector.support_]
print(f"Optimal number of features: {selector.n_features_}")
print(f"Selected features: {optimal_features.tolist()}")

# Evaluate the model
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
print(classification_report(y_test, y_pred))

# Print the model coefficients for logistic regression
# Note: We only get coefficients for Logistic Regression, which are not directly accessible through a pipeline.
# You would need to access the 'classifier' step of the pipeline after fitting.
# For example: pipeline.named_steps['classifier'].coef_

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

In [ ]:
df_with_constant = add_constant(X_train_smote)
vif_data = pd.DataFrame()
vif_data["feature"] = df_with_constant.columns

vif_data["VIF"] = [variance_inflation_factor(df_with_constant.values, i)
                   for i in range(df_with_constant.shape[1])]

print(vif_data)

In [ ]:
X.dtypes

In [ ]:
df